import type { ShelfCollection } from "./types";

export const SAMPLE_COLLECTIONS: ShelfCollection[] = [
  {
    id: "col-1",
    name: "Books That Changed How I Think",
    icon: "📚",
    description: "Non-fiction that reshaped my perspective on technology, society, and leadership",
    color: "#d97706",
    visibility: "public",
    createdAt: "2026-01-10T10:00:00Z",
    items: [
      {
        id: "item-1",
        title: "The Master Switch — Tim Wu",
        note: "Essential reading for anyone thinking about open vs. closed systems. The cycle Wu describes — open innovation → consolidation → monopoly → disruption — maps directly onto what AT Protocol is trying to break.",
        tags: ["tech", "history", "open-web"],
        rating: 5,
        createdAt: "2026-01-10T10:01:00Z",
      },
      {
        id: "item-2",
        title: "Seeing Like a State — James C. Scott",
        note: "The concept of 'legibility' is incredibly relevant to protocol design. Centralized systems optimize for legibility at the cost of local knowledge. Decentralized protocols preserve it.",
        tags: ["systems", "governance"],
        rating: 5,
        createdAt: "2026-01-12T10:00:00Z",
      },
      {
        id: "item-3",
        title: "An Elegant Puzzle — Will Larson",
        note: "Best book on engineering leadership I've read. The sections on organizational design and managing technical migrations apply directly to scaling a protocol team.",
        tags: ["leadership", "engineering"],
        rating: 4,
        createdAt: "2026-01-15T10:00:00Z",
      },
      {
        id: "item-4",
        title: "Protocol — Alexander Galloway",
        note: "Dense but rewarding. Galloway argues that protocols ARE the power structures of networked society. Mandatory reading before designing one.",
        tags: ["theory", "protocols"],
        rating: 4,
        createdAt: "2026-01-20T10:00:00Z",
      },
    ],
  },
  {
    id: "col-2",
    name: "Decentralization Reading List",
    icon: "🔗",
    description: "Articles, posts, and resources about decentralized social, AT Protocol, and the open web",
    color: "#0891b2",
    visibility: "public",
    createdAt: "2026-01-15T10:00:00Z",
    items: [
      {
        id: "item-5",
        title: "ATProto Ethos — Bluesky Blog",
        note: "The philosophical foundation. 'Speech vs. Reach' as separate layers is the key insight that differentiates AT Protocol from ActivityPub.",
        url: "https://atproto.com/articles/atproto-ethos",
        tags: ["atproto", "philosophy"],
        rating: 5,
        createdAt: "2026-01-15T10:01:00Z",
      },
      {
        id: "item-6",
        title: "Where It's at:// — Dan Abramov",
        note: "Best explanation of AT URIs and DIDs I've found. Dan has a gift for making complex concepts feel obvious.",
        url: "https://danabra.mov/at",
        tags: ["atproto", "explainer"],
        rating: 5,
        atUri: "at://danabra.mov/app.bsky.feed.post/3l4example",
        createdAt: "2026-01-16T10:00:00Z",
      },
      {
        id: "item-7",
        title: "Introduction to AT Protocol — mackuba.eu",
        note: "Incredibly thorough technical walkthrough. The sections on AppViews and Lexicons are the best available.",
        url: "https://mackuba.eu/2025/08/20/introduction-to-atproto/",
        tags: ["atproto", "technical"],
        rating: 5,
        createdAt: "2026-01-18T10:00:00Z",
      },
      {
        id: "item-8",
        title: "Bluesky and the AT Protocol — Christine Lemmer-Webber",
        note: "Important critical perspective. The concerns about PLC Directory centralization are valid and worth sitting with.",
        tags: ["atproto", "critique"],
        rating: 4,
        createdAt: "2026-01-22T10:00:00Z",
      },
    ],
  },
  {
    id: "col-3",
    name: "Atmosphere Apps to Try",
    icon: "🌐",
    description: "Apps built on AT Protocol that I'm exploring and evaluating",
    color: "#7c3aed",
    visibility: "public",
    createdAt: "2026-02-01T10:00:00Z",
    items: [
      {
        id: "item-9",
        title: "Frontpage — Link Aggregator",
        note: "HN-style link sharing on AT Protocol. First AppView that wasn't microblogging. Clean, fast, demonstrates custom Lexicons well.",
        url: "https://frontpage.fyi",
        tags: ["app", "links"],
        rating: 4,
        createdAt: "2026-02-01T10:01:00Z",
      },
      {
        id: "item-10",
        title: "Smoke Signal — Events & RSVPs",
        note: "Events platform with OAuth login. The developer (Nick Gerakines) writes excellent blog posts about building on ATProto. Worth following his journey.",
        url: "https://smokesignal.events",
        tags: ["app", "events"],
        rating: 4,
        createdAt: "2026-02-03T10:00:00Z",
      },
      {
        id: "item-11",
        title: "WhiteWind — Long-form Blogging",
        note: "The first custom Lexicon on AT Protocol. Japanese developer. Proved the network could support more than Bluesky. Historically significant.",
        url: "https://whtwnd.com",
        tags: ["app", "writing"],
        rating: 5,
        createdAt: "2026-02-05T10:00:00Z",
      },
      {
        id: "item-12",
        title: "Recipe Exchange",
        note: "Recipe data as open, structured Lexicon records. This is the kind of domain-specific app that demonstrates AT Protocol's potential beyond social.",
        url: "https://recipe.exchange",
        tags: ["app", "food"],
        rating: 4,
        createdAt: "2026-02-07T10:00:00Z",
      },
      {
        id: "item-13",
        title: "Roomy — P2P Messaging",
        note: "Discord-like chat using ATProto for identity + Automerge for P2P sync. Experimental but fascinating architecture. Touches the private data frontier.",
        tags: ["app", "messaging"],
        rating: 3,
        createdAt: "2026-02-10T10:00:00Z",
      },
    ],
  },
];
